/*
 * This file is generated by jOOQ.
 */
package org.example;


import org.example.tables.Movie;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.movie</code>.
     */
    public static final Movie MOVIE = Movie.MOVIE;
}
