/*
 * This file is generated by jOOQ.
 */
package org.example;


import org.example.tables.MyTable;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.my_table</code>.
     */
    public static final MyTable MY_TABLE = MyTable.MY_TABLE;
}
