/*
 * This file is generated by jOOQ.
 */
package org.example.tables.records;


import org.example.tables.MyTable;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MyTableRecord extends TableRecordImpl<MyTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.my_table.a_3bit</code>.
     */
    public void setA_3bit(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.my_table.a_3bit</code>.
     */
    public String getA_3bit() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MyTableRecord
     */
    public MyTableRecord() {
        super(MyTable.MY_TABLE);
    }

    /**
     * Create a detached, initialised MyTableRecord
     */
    public MyTableRecord(String a_3bit) {
        super(MyTable.MY_TABLE);

        setA_3bit(a_3bit);
        resetChangedOnNotNull();
    }
}
